---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    requirements-file: molecule/default/requirements.yml
driver:
  name: docker
platforms:
  - name: zookeeper-1
    image: geerlingguy/docker-debian13-ansible:latest
    docker_networks:
      - name: zookeeper
        ipam_config:
          - subnet: '172.26.0.0/16'
    networks:
      - name: zookeeper
        ipv4_address: '172.26.10.1'
    etc_hosts: "{'zookeeper-2': '172.26.10.2', 'zookeeper-3': '172.26.10.3'}"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    capabilities:
      - SYS_ADMIN
    command: /lib/systemd/systemd
    groups:
      - zookeeper-nodes
  - name: zookeeper-2
    image: redhat/ubi9:latest
    networks:
      - name: zookeeper
        ipv4_address: '172.26.10.2'
    etc_hosts: "{'zookeeper-1': '172.26.10.1', 'zookeeper-3': '172.26.10.3'}"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: '/usr/lib/systemd/systemd'
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    groups:
      - zookeeper-nodes
  - name: zookeeper-3
    image: redhat/ubi9:latest
    networks:
      - name: zookeeper
        ipv4_address: '172.26.10.3'
    etc_hosts: "{'zookeeper-1': '172.26.10.1', 'zookeeper-2': '172.26.10.2'}"
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: '/usr/lib/systemd/systemd'
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    groups:
      - zookeeper-nodes
provisioner:
  name: ansible
  env:
    # Molecule used to add ${MOLECULE_PROJECT_DIRECTORY}/. to this
    # path for us pre-25.2.0, but now we have to do it ourselves.  See
    # ansible/molecule#4380 and
    # https://github.com/ansible/molecule/releases/tag/v25.2.0 for
    # more details.
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..:~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
  inventory:
    host_vars:
      # The zookeeper_id is not provided for zookeeper-1 as this
      # should use the value of 1 from the defaults.
      zookeeper-1:
      zookeeper-2:
        zookeeper_id: 2
      zookeeper-3:
        zookeeper_id: 3
verifier:
  name: ansible
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
