---
- name: Prepare
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: Install python-firewall
      ansible.builtin.yum:
        name:
          - python3-firewall
        state: installed
      when: ansible_facts["os_family"] == "RedHat"

    - name: Install Java 8 (OpenJDK) on RedHat/CentOS
      ansible.builtin.yum:
        name: java-1.8.0-openjdk
        state: installed
      when: ansible_facts["os_family"] == "RedHat"

    - name: Install Java on Debian
      ansible.builtin.apt:
        name: default-jre
        state: present
        update_cache: yes
      when: ansible_facts["os_family"] == "Debian"

    # The installation of this package into the container means
    # that the "ps" command is available for viewing the running process.
    # Installing this package however also prevents an issue whereby the
    # ZooKeeper service is constantly restarted by systemd which causes
    # the Molecule tests to fail as the service is not started correctly.
    - name: Install ps on Debian
      ansible.builtin.apt:
        name: procps
        state: present
      when: ansible_facts["os_family"] == "Debian"

    - name: Install ps on RedHat/CentOS
      ansible.builtin.yum:
        name: procps
        state: present
      when: ansible_facts["os_family"] == "RedHat"
