---
name: Ansible Lint

#
# Documentation:
# https://github.com/ansible/ansible-lint-action
#
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Ansible Role
        uses: ansible/ansible-lint-action@master
        with:
          targets: ''
